import 'package:cloud_firestore/cloud_firestore.dart';

class LocationHistory {
  final String? locationID; // Auto-generated by Firestore
  final String userID; // Foreign Key (User)
  final double latitude; // Separate Latitude Field
  final double longitude; // Separate Longitude Field
  final Timestamp timeStamp; // Firestore Timestamp

  LocationHistory({
    this.locationID, // Firestore generates this
    required this.userID,
    required this.latitude,
    required this.longitude,
    required this.timeStamp,
  });

  Map<String, dynamic> toMap() {
    return {
      "userId": userID,
      "latitude": latitude, // Now stored separately
      "longitude": longitude,
      "timestamp": timeStamp,
    };
  }

  factory LocationHistory.fromMap(String id, Map<String, dynamic> map) {
    return LocationHistory(
      locationID: id,
      userID: map["userId"] ?? "",
      latitude: map["latitude"] ?? 0.0,
      longitude: map["longitude"] ?? 0.0,
      timeStamp: map["timestamp"] ?? Timestamp.now(),
    );
  }
}


