import 'package:login/database_service.dart';

class RecordedVoice {
  final String? voiceID; // Auto-generated by Firestore
  final String userID; // Foreign Key (User)
  final String voicePath; // Path to the stored recorded voice file

  RecordedVoice({
    this.voiceID, // Firestore will generate this automatically
    required this.userID,
    required this.voicePath,
  });

  Map<String, dynamic> toMap() {
    return {
      "userId": userID,
      "voicePath": voicePath, // File location (e.g., Firebase Storage)
    };
  }

  factory RecordedVoice.fromMap(String id, Map<String, dynamic> map) {
    return RecordedVoice(
      voiceID: id,
      userID: map["userId"] ?? "",
      voicePath: map["voicePath"] ?? "",
    );
  }
}

void saveVoicePath() async {
  RecordedVoice voice = RecordedVoice(
    userID: "USER_ID_HERE", // Replace with actual user ID
    voicePath: "storage/emulated/0/recordings/emergency_alert.mp3",
  );

  await DatabaseService().saveRecordedVoice(voice);
  print("Voice recording saved!");
}