// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB0jp0zg5l3rIHlkc047yh3rOiU7qzGOo',
    appId: '1:67133767058:web:b5154a9641b2476f99554b',
    messagingSenderId: '67133767058',
    projectId: 'login-4b242',
    authDomain: 'login-4b242.firebaseapp.com',
    storageBucket: 'login-4b242.firebasestorage.app',
    measurementId: 'G-47RYSJMCGK',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-uEOzql5kb-aIlz_PgX9zrk-RkxFmqKY',
    appId: '1:67133767058:ios:30d137f5607946e199554b',
    messagingSenderId: '67133767058',
    projectId: 'login-4b242',
    storageBucket: 'login-4b242.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-uEOzql5kb-aIlz_PgX9zrk-RkxFmqKY',
    appId: '1:67133767058:ios:30d137f5607946e199554b',
    messagingSenderId: '67133767058',
    projectId: 'login-4b242',
    storageBucket: 'login-4b242.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB0jp0zg5l3rIHlkc047yh3rOiU7qzGOo',
    appId: '1:67133767058:web:2a5ffdc9324e9cbc99554b',
    messagingSenderId: '67133767058',
    projectId: 'login-4b242',
    authDomain: 'login-4b242.firebaseapp.com',
    storageBucket: 'login-4b242.firebasestorage.app',
    measurementId: 'G-GGB09KBP6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlnGdUQyTbnpJSpDTD2_MIBJSz0kOOGuM',
    appId: '1:67133767058:android:5b17de0d7c309d3e99554b',
    messagingSenderId: '67133767058',
    projectId: 'login-4b242',
    storageBucket: 'login-4b242.firebasestorage.app',
  );

}